### ISSUE TITLE
Bug at coco dataset

### ISSUE THREAD

**Issue by E1eMenta** [HRNet/HRNet-Object-Detection#1]
Line bug https://github.com/HRNet/HRNet-Object-Detection/blob/4d257bf0a41d265f3b262347fb67b8f6330b86b7/mmdet/datasets/coco.py#L39

`def lget_ann_info(self, idx):`
instead of 
`
def get_ann_info(self, idx):`

**Comment by wondervictor** [comment]
Thanks, this line was modified by accidental operations. I'll fix it now.

**Comment by wondervictor** [comment]
fixed
