### ISSUE TITLE
how to use the specifed gpu 

### ISSUE THREAD

**Issue by aakunkun** [HRNet/HRNet-Object-Detection#14]

**Comment by aakunkun** [comment]
there are 8 gpus, the id is 0,1,2,3,4,5,6,7, I ues the CUDA_VISIBLE_DEVICES=4,5,6,7 ,but it doesn't work

**Comment by wondervictor** [comment]
`CUDA_VISIBLE_DEVICES=4,5,6,7 python -m torch.distributed.launch --nproc_per_node 4 tools/train.py` works.

**Comment by wondervictor** [comment]
No more response. closed
