### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by guaiwuguba** [HRNet/HRNet-Object-Detection#15]
The size of image of mmdetection is (1333, 800), but my own data is (2048, 1080). what can I do and the action will not hve bad effects?

**Comment by wondervictor** [comment]
1. decrease your input size, or using the default input size
2. use GPU with large memory (16GB or 24GB)
3. decrease your batch size (default is 2)

**Comment by wondervictor** [comment]
closed!
