### ISSUE TITLE
Image size!

### ISSUE THREAD

**Issue by guaiwuguba** [HRNet/HRNet-Object-Detection#16]
I use the config of cascade and hrnet! But it seems that this network occupies too many memories so that the dataset I make (2048, 1080) results in out of memory! If I crop the dataset (1333, 800), that will cause low map! So what should I do now? Please!

**Comment by wondervictor** [comment]
your input size (2080, 1080) is too large! you need to decrease batchsize to 1 !

**Comment by guaiwuguba** [comment]
Yeah! I have already set the imgs_per_gpu=1~ I want to know the max size of this config?




------------------ 原始邮件 ------------------
发件人: "Tianheng Cheng"<notifications@github.com>;
发送时间: 2019年7月24日(星期三) 上午10:47
收件人: "HRNet/HRNet-Object-Detection"<HRNet-Object-Detection@noreply.github.com>;
抄送: "郭彤彤"<1905919813@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [HRNet/HRNet-Object-Detection] Image size! (#16)




your input size (2080, 1080) is too large! you need to decrease batchsize to 1 !

**Comment by wondervictor** [comment]
We haven't made clear the max size that one GPU can hold. Different GPU has a different memory.

**Comment by guaiwuguba** [comment]
Thank you very much! I have a try latter!




------------------ 原始邮件 ------------------
发件人: "Tianheng Cheng"<notifications@github.com>;
发送时间: 2019年7月24日(星期三) 上午10:55
收件人: "HRNet/HRNet-Object-Detection"<HRNet-Object-Detection@noreply.github.com>;
抄送: "郭彤彤"<1905919813@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [HRNet/HRNet-Object-Detection] Image size! (#16)




We haven't made clear the max size that one GPU can hold. Different GPU has a different memory.
