### ISSUE TITLE
some problem about torch

### ISSUE THREAD

**Issue by DangerousY** [HRNet/HRNet-Object-Detection#17]
When I comile the ./compile.sh, I meet with those problems. My torch version is 0.4.1, CUDA is 9.0, and CUDNN is 7.0. And I don;t know how to solve it. Those four similar problems. 
src/roi_align_cuda.cpp:1:29: fatal error: torch/extension.h: No such file or directory
..
..
src/deform_conv_cuda.cpp:4:29: fatal error: torch/extension.h: No such file or directory

**Comment by wondervictor** [comment]
Only support torch >= 1.0.1
