### ISSUE TITLE
提供一下预训练模型的权重下载啊。

### ISSUE THREAD

**Issue by xujin1184104394** [HRNet/HRNet-Object-Detection#18]
为什么要使用微软云盘，打开什么都没有？？？

**Comment by wondervictor** [comment]
For pretrained models, you can download them through [HRNet-Image-Classification](https://github.com/HRNet/HRNet-Image-Classification
Models trained on COCO will be updated soon.

**Comment by wondervictor** [comment]
Duplicate of #20

**Comment by wondervictor** [comment]
All models have been uploaded to BaiduDrive. Links are listed in README
