### ISSUE TITLE
Pretrained models are not easily accessible

### ISSUE THREAD

**Issue by bkcompton** [HRNet/HRNet-Object-Detection#20]
One needs to register on Baidu with a Chinese phone number. 

It would be great if these could be shared outside of Baidu.

**Comment by wondervictor** [comment]
For pretrained models, you can download them through [HRNet-Image-Classification](https://github.com/HRNet/HRNet-Image-Classification
Models trained on COCO will be updated soon.

**Comment by bkcompton** [comment]
Thank you!!!
