### ISSUE TITLE
w40 model's map=0.000

### ISSUE THREAD

**Issue by aakunkun** [HRNet/HRNet-Object-Detection#22]
the model doesn't work,all the ap values are 0.000

**Comment by wondervictor** [comment]
Please provide more details.

**Comment by aakunkun** [comment]
I test the model on coco with the method of mmdetection，but all the
test value is 0




| |
zekun0227
邮箱：zekun0227@163.com
|

Signature is customized by Netease Mail Master

On 09/08/2019 09:59, Tianheng Cheng wrote:

Please provide more details.

**Comment by wondervictor** [comment]
May you provide your 'config' file.
Our code has some modifications compared with the official mmdetection.

**Comment by DangerousY** [comment]
> May you provide your 'config' file.
> Our code has some modifications compared with the official mmdetection.

I meet with the same problem, i have 10 classes and i use faster_rcnn_hrnetv2p_w18_1x.py. I change it a little. This
![9b54d7473c5917173ca006b89cbc7f1](https://user-images.githubusercontent.com/37180463/65813347-cd169080-e206-11e9-9948-4396ec45fed0.png)
![5e1fbe4b3eaefca7fe8b1d87f3b3938](https://user-images.githubusercontent.com/37180463/65813350-cf78ea80-e206-11e9-9ca1-33b691f105f4.png)
![399d23ed0c571ce35fa867fae08fbf1](https://user-images.githubusercontent.com/37180463/65813353-d3a50800-e206-11e9-90b5-537e6e3f2ebe.png)
![dd17adc51f412042fcd6f3fce00d29f](https://user-images.githubusercontent.com/37180463/65813354-d4d63500-e206-11e9-97d2-ec8f89fbc0ad.png)



 is my config file

**Comment by wondervictor** [comment]
1. You didn't change the `num_classes` in `config` file, it still outputs 81 classes
2. Pretrained model is necessary. We didn't test training w/o pre-trained model because the FROZEN BN is not correctly initialized.
3. If those mentioned above cannot solve your problem, please check your data and your annotations. We can not guarantee that your data and the corresponding annotations are absolutely reliable.
Confidently, we have tested out code in both training and testing phases and we can obtain better results than ResNets and ResNeXts.

**Comment by DangerousY** [comment]
> 1. You didn't change the `num_classes` in `config` file, it still outputs 81 classes
> 2. Pretrained model is necessary. We didn't test training w/o pre-trained model because the FROZEN BN is not correctly initialized.
> 3. If those mentioned above cannot solve your problem, please check your data and your annotations. We can not guarantee that your data and the corresponding annotations are absolutely reliable.
> 
> _Confidently_, we have tested out code in both training and testing phases and we can obtain better results than ResNets and ResNeXts.

When I change the num_classes to 10, there is a RuntimeError
bbox_targets_expand[i, start:end] = bbox_targets[i, :]
RuntimeError: The expanded size of the tensor (0) must match the existing size (4) at non-singleton dimension 0.  Target sizes: [0].  Tensor sizes: [4]
it means that my data form has some problems?

**Comment by DangerousY** [comment]
I have solved it, because numclass=your object calss + 1; i have 10 classes, so numclasses i need to use 11

**Comment by DangerousY** [comment]
> 1. You didn't change the `num_classes` in `config` file, it still outputs 81 classes
> 2. Pretrained model is necessary. We didn't test training w/o pre-trained model because the FROZEN BN is not correctly initialized.
> 3. If those mentioned above cannot solve your problem, please check your data and your annotations. We can not guarantee that your data and the corresponding annotations are absolutely reliable.
> 
> _Confidently_, we have tested out code in both training and testing phases and we can obtain better results than ResNets and ResNeXts.

Thanks, it works!

**Comment by wondervictor** [comment]
Solved, close
