### ISSUE TITLE
 WARNING - The model and loaded state dict do not match exactly,

### ISSUE THREAD

**Issue by YijianLiu** [HRNet/HRNet-Object-Detection#29]
When I am training my own dataset,  it doesn't occur any error, but it can't run successfully, can you help me? Thanks very much!!!!
python -m torch.distributed.launch --nproc_per_node 2 to
ols/train.py configs/hrnet/potsdam.py --launcher pytorch
2019-09-29 14:00:51,640 - INFO - Distributed training: True
2019-09-29 14:00:52,039 - INFO - load model from: hrnetv2_pretrained/hrnetv2_w18.pth
2019-09-29 14:00:52,171 - WARNING - The model and loaded state dict do not match exactly

unexpected key in source state_dict: incre_modules.0.0.conv1.weight, incre_modules.0.0.bn1.weight, incre_modules.0.0.bn1.bias, incre_modules.0.0.bn1.running_mean, incre_modules.0.0.bn1.running_var, incre_modules.0.0.bn1.num_batches_tracked, incre_modules.0.0.conv2.weight, incre_modules.0.0.bn2.weight, incre_modules.0.0.bn2.bias, incre_modules.0.0.bn2.running_mean, incre_modules.0.0.bn2.running_var, incre_modules.0.0.bn2.num_batches_tracked, incre_modules.0.0.conv3.weight, incre_modules.0.0.bn3.weight, incre_modules.0.0.bn3.bias, incre_modules.0.0.bn3.running_mean, incre_modules.0.0.bn3.running_var, incre_modules.0.0.bn3.num_batches_tracked, incre_modules.0.0.downsample.0.weight, incre_modules.0.0.downsample.1.weight, incre_modules.0.0.downsample.1.bias, incre_modules.0.0.downsample.1.running_mean, incre_modules.0.0.downsample.1.running_var, incre_modules.0.0.downsample.1.num_batches_tracked, incre_modules.1.0.conv1.weight, incre_modules.1.0.bn1.weight, incre_modules.1.0.bn1.bias, incre_modules.1.0.bn1.running_mean, incre_modules.1.0.bn1.running_var, incre_modules.1.0.bn1.num_batches_tracked, incre_modules.1.0.conv2.weight, incre_modules.1.0.bn2.weight, incre_modules.1.0.bn2.bias, incre_modules.1.0.bn2.running_mean, incre_modules.1.0.bn2.running_var, incre_modules.1.0.bn2.num_batches_tracked, incre_modules.1.0.conv3.weight, incre_modules.1.0.bn3.weight, incre_modules.1.0.bn3.bias, incre_modules.1.0.bn3.running_mean, incre_modules.1.0.bn3.running_var, incre_modules.1.0.bn3.num_batches_tracked, incre_modules.1.0.downsample.0.weight, incre_modules.1.0.downsample.1.weight, incre_modules.1.0.downsample.1.bias, incre_modules.1.0.downsample.1.running_mean, incre_modules.1.0.downsample.1.running_var, incre_modules.1.0.downsample.1.num_batches_tracked, incre_modules.2.0.conv1.weight, incre_modules.2.0.bn1.weight, incre_modules.2.0.bn1.bias, incre_modules.2.0.bn1.running_mean, incre_modules.2.0.bn1.running_var, incre_modules.2.0.bn1.num_batches_tracked, incre_modules.2.0.conv2.weight, incre_modules.2.0.bn2.weight, incre_modules.2.0.bn2.bias, incre_modules.2.0.bn2.running_mean, incre_modules.2.0.bn2.running_var, incre_modules.2.0.bn2.num_batches_tracked, incre_modules.2.0.conv3.weight, incre_modules.2.0.bn3.weight, incre_modules.2.0.bn3.bias, incre_modules.2.0.bn3.running_mean, incre_modules.2.0.bn3.running_var, incre_modules.2.0.bn3.num_batches_tracked, incre_modules.2.0.downsample.0.weight, incre_modules.2.0.downsample.1.weight, incre_modules.2.0.downsample.1.bias, incre_modules.2.0.downsample.1.running_mean, incre_modules.2.0.downsample.1.running_var, incre_modules.2.0.downsample.1.num_batches_tracked, incre_modules.3.0.conv1.weight, incre_modules.3.0.bn1.weight, incre_modules.3.0.bn1.bias, incre_modules.3.0.bn1.running_mean, incre_modules.3.0.bn1.running_var, incre_modules.3.0.bn1.num_batches_tracked, incre_modules.3.0.conv2.weight, incre_modules.3.0.bn2.weight, incre_modules.3.0.bn2.bias, incre_modules.3.0.bn2.running_mean, incre_modules.3.0.bn2.running_var, incre_modules.3.0.bn2.num_batches_tracked, incre_modules.3.0.conv3.weight, incre_modules.3.0.bn3.weight, incre_modules.3.0.bn3.bias, incre_modules.3.0.bn3.running_mean, incre_modules.3.0.bn3.running_var, incre_modules.3.0.bn3.num_batches_tracked, incre_modules.3.0.downsample.0.weight, incre_modules.3.0.downsample.1.weight, incre_modules.3.0.downsample.1.bias, incre_modules.3.0.downsample.1.running_mean, incre_modules.3.0.downsample.1.running_var, incre_modules.3.0.downsample.1.num_batches_tracked, downsamp_modules.0.0.weight, downsamp_modules.0.0.bias, downsamp_modules.0.1.weight, downsamp_modules.0.1.bias, downsamp_modules.0.1.running_mean, downsamp_modules.0.1.running_var, downsamp_modules.0.1.num_batches_tracked, downsamp_modules.1.0.weight, downsamp_modules.1.0.bias, downsamp_modules.1.1.weight, downsamp_modules.1.1.bias, downsamp_modules.1.1.running_mean, downsamp_modules.1.1.running_var, downsamp_modules.1.1.num_batches_tracked, downsamp_modules.2.0.weight, downsamp_modules.2.0.bias, downsamp_modules.2.1.weight, downsamp_modules.2.1.bias, downsamp_modules.2.1.running_mean, downsamp_modules.2.1.running_var, downsamp_modules.2.1.num_batches_tracked, final_layer.0.weight, final_layer.0.bias, final_layer.1.weight, final_layer.1.bias, final_layer.1.running_mean, final_layer.1.running_var, final_layer.1.num_batches_tracked, classifier.weight, classifier.bias

loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
loading annotations into memory...
Done (t=0.02s)
creating index...
index created!
loading annotations into memory...
loading annotations into memory...
Done (t=0.01s)
creating index...
Done (t=0.01s)
index created!creating index...

index created!
2019-09-29 14:00:57,339 - INFO - Start running, host: eagle2019@yang-Precision-Tower-7910, work_dir: /server_space/liuyj/apex/HRNet-Object-Detection/work_dirs/faster_rcnn_hrnetv2p_w18_1x
2019-09-29 14:00:57,339 - INFO - workflow: [('train', 1)], max: 12 epochs
/home/eagle2019/.conda/envs/HRNet_object_detec/lib/python3.7/site-packages/torch/nn/modules/upsampling.py:129: UserWarning: nn.Upsample is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.{} is deprecated. Use nn.functional.interpolate instead.".format(self.name))
/home/eagle2019/.conda/envs/HRNet_object_detec/lib/python3.7/site-packages/torch/nn/modules/upsampling.py:129: UserWarning: nn.Upsample is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.{} is deprecated. Use nn.functional.interpolate instead.".format(self.name))
/home/eagle2019/.conda/envs/HRNet_object_detec/lib/python3.7/site-packages/torch/nn/functional.py:2423: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
/home/eagle2019/.conda/envs/HRNet_object_detec/lib/python3.7/site-packages/torch/nn/functional.py:2423: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))

**Comment by wondervictor** [comment]
It doesn't matter. These parameters belong to classification-head for ImageNet classification.

**Comment by YijianLiu** [comment]
> It doesn't matter. These parameters belong to classification-head for ImageNet classification.

Thanks very much, can you check my log above again, it doesn't occur any errors but it can't run successfully.

**Comment by YijianLiu** [comment]
> It doesn't matter. These parameters belong to classification-head for ImageNet classification.
As you can see this log , it seems don't occur any error, and it seems begin starting run, but in fact it doesn't run actually and successfully, I have check my own dataset again, it doesn't matter, can you help me? Thanks!  
loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
loading annotations into memory...
Done (t=0.02s)
creating index...
index created!
loading annotations into memory...
loading annotations into memory...
Done (t=0.01s)
creating index...
Done (t=0.01s)
index created!creating index...

index created!
2019-09-29 14:00:57,339 - INFO - Start running, host: eagle2019@yang-Precision-Tower-7910, work_dir: /apex/HRNet-Object-Detection/work_dirs/faster_rcnn_hrnetv2p_w18_1x
2019-09-29 14:00:57,339 - INFO - workflow: [('train', 1)], max: 12 epochs
/home/eagle2019/.conda/envs/HRNet_object_detec/lib/python3.7/site-packages/torch/nn/modules/upsampling.py:129: UserWarning: nn.Upsample is deprecated. Use nn.functional.interpolate instead.
warnings.warn("nn.{} is deprecated. Use nn.functional.interpolate instead.".format(self.name))
/home/.conda/envs/HRNet_object_detec/lib/python3.7/site-packages/torch/nn/modules/upsampling.py:129: UserWarning: nn.Upsample is deprecated. Use nn.functional.interpolate instead.
warnings.warn("nn.{} is deprecated. Use nn.functional.interpolate instead.".format(self.name))
/home/.conda/envs/HRNet_object_detec

**Comment by wondervictor** [comment]
**These parameters belong to classification-head for ImageNet classification.** The pretrained model contains the parameters of `classification head` while HRNet-Object-Detection doesn't need `classification-head`, so these parameters are redundant.

**Comment by YijianLiu** [comment]
> **These parameters belong to classification-head for ImageNet classification.** The pretrained model contains the parameters of `classification head` while HRNet-Object-Detection doesn't need `classification-head`, so these parameters are redundant.
Thanks so much, but now I meet the biggest question is that it doesn't occur any error, but it can't doesn't occur any training log like "...Epoch [1] 1/5000..", it just stop training suddenly with nothing,
the log is as followed:
2019-09-29 14:00:57,339 - INFO - Start running, host: eagle2019@yang-Precision-Tower-7910, work_dir: /apex/HRNet-Object-Detection/work_dirs/faster_rcnn_hrnetv2p_w18_1x
2019-09-29 14:00:57,339 - INFO - workflow: [('train', 1)], max: 12 epochs
(As you can see here, the next line must occur the training logs, but it occurs nothing and just stop the training with nothing occurs.)

**Comment by wondervictor** [comment]
more details, your command. Maybe training is slow.

**Comment by YijianLiu** [comment]
> more details, your command. Maybe training is slow.
My cmd is “python -m torch.distributed.launch --nproc_per_node 2 to
ols/train.py configs/hrnet/potsdam.py --launcher pytorch”, when I train it, it doesn't occupy any gpu, but when I train it on another server, it trains successfully, both of them have the same log except one doesn't begin train. Thanks so much!
My log is:
2019-09-29 14:00:51,640 - INFO - Distributed training: True
2019-09-29 14:00:52,039 - INFO - load model from: hrnetv2_pretrained/hrnetv2_w18.pth
loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
loading annotations into memory...
Done (t=0.02s)
creating index...
index created!
loading annotations into memory...
loading annotations into memory...
Done (t=0.01s)
creating index...
Done (t=0.01s)
index created!creating index...
index created!
2019-09-29 14:00:57,339 - INFO - Start running, host: eagle2019@yang-Precision-Tower-7910, work_dir: /server_space/liuyj/apex/HRNet-Object-Detection/work_dirs/faster_rcnn_hrnetv2p_w18_1x
2019-09-29 14:00:57,339 - INFO - workflow: [('train', 1)], max: 12 epochs
/home/eagle2019/.conda/envs/HRNet_object_detec/lib/python3.7/site-packages/torch/nn/modules/upsampling.py:129: UserWarning: nn.Upsample is deprecated. Use nn.functional.interpolate instead.
warnings.warn("nn.{} is deprecated. Use nn.functional.interpolate instead.".format(self.name))
/home/eagle2019/.conda/envs/HRNet_object_detec/lib/python3.7/site-packages/torch/nn/modules/upsampling.py:129: UserWarning: nn.Upsample is deprecated. Use nn.functional.interpolate instead.
warnings.warn("nn.{} is deprecated. Use nn.functional.interpolate instead.".format(self.name))
/home/eagle2019/.conda/envs/HRNet_object_detec/lib/python3.7/site-packages/torch/nn/functional.py:2423: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
"See the documentation of nn.Upsample for details.".format(mode))
/home/eagle2019/.conda/envs/HRNet_object_detec/lib/python3.7/site-packages/torch/nn/functional.py:2423: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
"See the documentation of nn.Upsample for details.".format(mode))

**Comment by wondervictor** [comment]
Another machine is fine. Errors may come from your environment or hardware.
