### ISSUE TITLE
Inconsistent with paper presentation

### ISSUE THREAD

**Issue by ZHANGHeng19931123** [HRNet/HRNet-Object-Detection#3]
很棒！但是在看了源码以后， 发现好像代码和文章配图的网络结构不符？我画了一个简图，在生成一个分辨率更低的branch的时候只使用了上一个stage分辨率最接近的feature maps？
![HRNet](https://user-images.githubusercontent.com/22428320/56418707-08945280-6298-11e9-974e-96601159120e.png)

期待您的回复

**Comment by wondervictor** [comment]
Hi, in our implementation, we split the last fusion in each stage into two parts: **fusion** and **transition**. We append a fusion module after every `HighResolutionModule`.  After fusing features from different resolutions, we then obtain the new branch by the last branch.  Actually, the figure presented in our paper is consistent with our implementation.
Thanks for your attention : )

**Comment by ZHANGHeng19931123** [comment]
Thanks a lot for your explanation! ^^ What you mean is that even though the new branch comes from one branch, but this branch contains information about different resolutions from the previous stage, is that right? And could you take a little time and confirm if my plot is correct, please?

**Comment by sunke123** [comment]
@ZHANGHeng19931123 
Hi Heng, your plot is more accurate.
In our paper, we emphasize that the output representations on different resolutions aggregate all the input representations. The two implementations are almost the same. You can check that.
![fusion](https://user-images.githubusercontent.com/11239351/56454401-8fbdf500-6382-11e9-9285-f2c999ae3a6d.jpg)

Hope this help you. If you have any question, welcome to contact us.

**Comment by ZHANGHeng19931123** [comment]
Thanks a lot! It's clear to me now :+1:

**Comment by X-tan58** [comment]
6

**Comment by shui-tian-ju-shi** [comment]
Thanks a lot!
