### ISSUE TITLE
Question about the HRNet to be used in other framework

### ISSUE THREAD

**Issue by DangerousY** [HRNet/HRNet-Object-Detection#30]
I want to ask if the HRNet which can be used in any objection detection framework as a Backbone. Is it possible that I just need to change the backbone to HRNet in some other framework.

**Comment by wondervictor** [comment]
[HRNet](https://arxiv.org/abs/1908.07919) is a general backbone which can be extended to quantities of tasks. It's possible that HRNet can be adapted to other frameworks. As for how we apply HRNet into kinds of tasks, our tech report provides more details ([Deep High-Resolution Representation Learning for Visual Recognition
](https://arxiv.org/abs/1908.07919))

**Comment by DangerousY** [comment]
Thanks！It helps me a lot.
