### ISSUE TITLE
OSError: /hrnetv2_pretrained/faster_rcnn_hrnetv2p_w32_mstrain_syncbn_1x.pth is not a checkpoint file

### ISSUE THREAD

**Issue by handsomefengfeng** [HRNet/HRNet-Object-Detection#32]
`python -m torch.distributed.launch --nproc_per_node 4 tools/train.py configs/hrnet/faster_rcnn_hrnetv2p_w32_syncbn_mstrain_1x.py --launcher pytorch
`
But the terminal output:
OSError: /hrnetv2_pretrained/faster_rcnn_hrnetv2p_w32_mstrain_syncbn_1x.pth is not a checkpoint file

I also tried hrnetv2_w44_imagenet_pretrained.pth, it obtained the same error.

What should I do????
 Thanks

**Comment by wondervictor** [comment]
`OSError: /hrnetv2_pretrained/faster_rcnn_hrnetv2p_w32_mstrain_syncbn_1x.pth ` this is a root directory.
'./hrnetv2_pretrained' please.

**Comment by handsomefengfeng** [comment]
T  T  sry for such an idiot mistake
thanks  !!! 
I've replaced it with absolute path.
