### ISSUE TITLE
shape problem

### ISSUE THREAD

**Issue by AugustusMJB** [HRNet/HRNet-Object-Detection#4]
when I use your hrnet, it caused a problem about shape mismatch
I found that it is because upsample mismatch with convolution_stride2,
in others words, convolution_stride2 is not absolutely 2 size downsample

so the fuse layer got shape mismatch.
how to solve it

**Comment by wondervictor** [comment]
Can you provide your information about your input, such as shape and etc?  In object detection, our input image has been padded to ensure that height and weight can be divided by 32. If you employ other shapes, you need to modify the fusion module like this:

* 1. remove the `nn.Upsample(scale_factor=2**(j-i), mode='nearest')` in `_make_fuse_layers` https://github.com/HRNet/HRNet-Object-Detection/blob/21a6d412aba9dd6935d862d631dd88cad57357be/mmdet/models/backbones/hrnet.py#L205

* 2. interpolate when `j > i` change line 243-253 into this:

````python
for i in range(len(self.fuse_layers)):
    y = x[0] if i == 0 else self.fuse_layers[i][0](x[0])
    for j in range(1, self.num_branches):
        if i == j:
            y = y + x[j]
        elif j > i:
            y = y + F.interpolate(
                self.fuse_layers[i][j](x[j]),
                size=[x[i].shape[2], x[i].shape[3]],
                mode='nearest')
        else:
            y = y + self.fuse_layers[i][j](x[j])
````


Convolution with stride 2 has the same output shape with MaxPool or AvgPool in Pytorch. when dilation rate is 1. You can refer to the pytorch documentation [Conv](https://pytorch.org/docs/stable/nn.html#torch.nn.Conv2d) and [MaxPool2D and AvgPool2D](https://pytorch.org/docs/stable/nn.html#pooling-layers)

**Comment by AugustusMJB** [comment]
I am very sorry  for late reply, I have fixed it by using F.interpolate in code,
thank you very much

**Comment by wondervictor** [comment]
Ok

**Comment by cassie101** [comment]
Hi @wondervictor, can't seem to find this in the model, may I know which line in the code is input image padded to ensure that height and weight can be divided by 32??

**Comment by wondervictor** [comment]
@cassie101 see: https://github.com/HRNet/HRNet-Object-Detection/blob/5da6db568d9e8f2d57e7adb99a7b4f6f0d864fde/configs/hrnet/faster_rcnn_hrnetv2p_w18_1x.py#L132
