### ISSUE TITLE
Question on Upsample

### ISSUE THREAD

**Issue by liuhengyue** [HRNet/HRNet-Object-Detection#44]
Hi, thanks for the great work. I do have a question on the upsample method. In the paper on mult-scale feature fusion, the upsample is "bilinear" followed by the 1x1 conv, but in the implementation I saw the Upsample kwarg is "nearest". Do I miss or miss-understand anything here? Btw, will it influence the feature representation much (based on your intuition or experiments).

**Comment by wondervictor** [comment]
@liuhengyue Hi, the upsampling in the backbone network (HRNet) is `nearest`. The influence here is neglectable.
