### ISSUE TITLE
Results of cascade_rcnn_hrnetv2p_w32

### ISSUE THREAD

**Issue by lijiannuist** [HRNet/HRNet-Object-Detection#5]
Hi @leoxiaobin 
When I use the cascade_rcnn_hrnetv2p_w32 model for inference on val2017.
I got 0.389, instead of 43.7mAP.
Why？

**Comment by wondervictor** [comment]
@lijiannuist I'll check it now.

**Comment by wondervictor** [comment]
@lijiannuist  I've tested Cascade R-CNN on *val2017* just and obtained the results below:
![image](https://user-images.githubusercontent.com/15026693/56725363-53720680-677f-11e9-8187-cfa371dbe730.png)

Can you provide more information about your modifications or how you migrate this code into your environment as well as data preprocessing.

**Comment by lijiannuist** [comment]
Amazing, I did not do any modification.
![捕获](https://user-images.githubusercontent.com/13388942/56731612-74d9ef00-678d-11e9-851f-7ecf9a80a8d5.JPG)

**Comment by wondervictor** [comment]
1. have you modified configurations for data in `cascade_rcnn_hrnetv2p_w32.py`?
2. do you use the downloaded model file ?

**Comment by lijiannuist** [comment]
I just change the data format, and did not use zip data.
because CocoZipDataset has bug.
![image](https://user-images.githubusercontent.com/13388942/56779867-87950800-680f-11e9-8be8-d9f5887981b2.png)

**Comment by lijiannuist** [comment]
Results of cascade_rcnn_r101_fpn
![image](https://user-images.githubusercontent.com/13388942/56782210-c1b6d780-6818-11e9-8ca7-5c9fe010ca44.png)

**Comment by wondervictor** [comment]
Can you provide part of your configurations about dataset.

**Comment by wondervictor** [comment]
> I just change the data format, and did not use zip data.
> because CocoZipDataset has bug.
> ![image](https://user-images.githubusercontent.com/13388942/56779867-87950800-680f-11e9-8be8-d9f5887981b2.png)

Images are not found in your `zip` file. not bug

**Comment by lijiannuist** [comment]
![image](https://user-images.githubusercontent.com/13388942/56784528-78b85080-6823-11e9-82ae-3085e5779f4c.png)

when I unzip zip file and use CocoDataset, it works and images are found.

**Comment by wondervictor** [comment]
You need to set `to_rgb=True` because `CocoDataset` default format is `BGR`

**Comment by lijiannuist** [comment]
Hi @wondervictor 
It works when to_rgb is set to be True

**Comment by wondervictor** [comment]
solved. I'll close it.
