### ISSUE TITLE
预训练模型不能下载,能更新一下链接吗?

### ISSUE THREAD

**Issue by Wulingtian** [HRNet/HRNet-Object-Detection#7]

**Comment by wondervictor** [comment]
Hi, there is something wrong with OneDrive server and it'll be ok soon. All models will be uploaded to Google Drive to make a backup.

**Comment by Wulingtian** [comment]
能加一个百度云链接吗？

**Comment by aakunkun** [comment]
Hi,the pretrained model can not downlaod

**Comment by Johnson13** [comment]
onedrive 访问不了。。。能不能加个百度云链接？

**Comment by xujin1184104394** [comment]
请问Google 云盘链接在哪？

**Comment by xujin1184104394** [comment]
> Hi, there is something wrong with OneDrive server and it'll be ok soon. All models will be uploaded to Google Drive to make a backup.

能提供一下 Google  Drive link？

**Comment by wondervictor** [comment]
#20

**Comment by wondervictor** [comment]
All models have been uploaded to BaiduDrive. Links are listed in README

**Comment by wondervictor** [comment]
@xujin1184104394 @Wulingtian @aakunkun @Johnson13 We've added BaiduDrive links already
