### ISSUE TITLE
The Issue about Distributed Training

### ISSUE THREAD

**Issue by xunhen** [HRNet/HRNet-Object-Detection#9]
Hello!
I have a question about the Distributed Training. 
What is the role of this parameter ‘coalesce’ ?
The Code is listed below:

def allreduce_grads(model, coalesce=True, bucket_size_mb=-1):
    grads = [
        param.grad.data for param in model.parameters()
        if param.requires_grad and param.grad is not None
    ]
    world_size = dist.get_world_size()
    if coalesce:
        _allreduce_coalesced(grads, world_size, bucket_size_mb)
    else:
        for tensor in grads:
            dist.all_reduce(tensor.div_(world_size))

If anybody answers, I'm grateful.

**Comment by wondervictor** [comment]
When using coalesce all reduce, tensors are distributed into different buckets determined by their types. Then tensors of the same type will be synchronized together. Without coalesce,  all tensors will be synchronized individually. In my opinion, using coalesce will synchronize more efficiently by making full use of buffers and bandwidth.

**Comment by xunhen** [comment]
Thank you very much! 

> When using coalesce all reduce, tensors are distributed into different buckets determined by their types. Then tensors of the same type will be synchronized together. For example, transmit all int tensors or all float tensors. Without coalesce, all tensors will be synchronized individually. In my opinion, using coalesce will synchronize more efficiently by making full use of buffers and bandwidth.

Thank you very much!
